# anorak_prep.yaml
images_dir: data/processed/ANORAK_not_resized/image
masks_dir: data/processed/ANORAK_not_resized/mask
out_dir: data/processed/tiles/ANORAK/tiles_224_10x_pad
source_mpp: 0.5
target_mpp: 1.0
tile_size: 224
stride: 224
pad_mode: pad
num_classes: 7
ignore_label: 0
min_foreground_ratio: 0.05
min_valid_pixel_ratio: 0.80